FROM node:22-alpine

WORKDIR /app

ARG VITE_API_BASE_URL=http://localhost:4000
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV PORT=3000

COPY . .

RUN npm ci && \
    npm run build --workspace core && \
    npm run build --workspace client

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start:prod", "--workspace", "client"]
